# Tên của quy trình làm việc (workflow)
name: Build Docker Image

# Điều kiện kích hoạt: Chạy workflow này mỗi khi có code được đẩy (push) lên nhánh `main`
on:
  push:
    branches: [ "main" ]

# Định nghĩa các công việc (jobs) sẽ được thực hiện
jobs:
  build:
    # Tên của công việc
    name: Build Docker Image
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest

    # Các bước thực hiện
    steps:
      # Bước 1: Lấy mã nguồn từ repository về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Build Docker image
      # Lỗi "no such file or directory" nghĩa là GitHub Actions không tìm thấy file Dockerfile.
      # Hãy đảm bảo file của bạn tên là 'Dockerfile' (phân biệt chữ hoa chữ thường) và nằm ở thư mục gốc của repository.
      # Nếu nó nằm ở một thư mục khác, hãy thay đổi giá trị của cờ --file bên dưới.
      # Ví dụ: --file Web/Dockerfile
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag my-app:latest .

