# Tên của quy trình làm việc (workflow)
name: Build Docker Image

# Điều kiện kích hoạt: Chạy workflow này mỗi khi có code được đẩy (push) lên nhánh `main`
on:
  push:
    branches: [ "main" ]

# Định nghĩa các công việc (jobs) sẽ được thực hiện
jobs:
  build:
    # Tên của công việc
    name: Build Docker Image
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest

    # Các bước thực hiện
    steps:
      # Bước 1: Lấy mã nguồn từ repository về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Liệt kê các file để kiểm tra đường dẫn (Debugging Step)
      # Bước này sẽ hiển thị toàn bộ cấu trúc thư mục của bạn trong nhật ký (logs) của Action.
      # Hãy xem nhật ký để tìm đúng đường dẫn đến Dockerfile của bạn.
      - name: List files in the repository
        run: ls -R

      # Bước 3: Build Docker image
      # Lỗi "no such file or directory" nghĩa là GitHub Actions không tìm thấy file Dockerfile.
      # Hãy xem kết quả của bước "List files in the repository" ở trên để tìm đúng đường dẫn.
      # Nếu Dockerfile của bạn nằm trong thư mục con, ví dụ `Web/Dockerfile`,
      # hãy thay đổi giá trị của cờ --file bên dưới thành --file Web/Dockerfile
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag my-app:latest .

